#!/bin/bash
# Setup GitHub Actions deployment for BluecoinsWeb

echo "🚀 Setting up GitHub Actions Auto-Deployment"
echo "=============================================="
echo ""

# Check if we're in the right directory
if [ ! -f "manage.py" ]; then
    echo "❌ Error: This script must be run from the BluecoinsWeb root directory"
    echo "Current directory: $(pwd)"
    echo "Please run: cd /opt/bluecoins-web && ./deploy/setup_github_actions.sh"
    exit 1
fi

echo "✅ GitHub Actions workflow file created at: .github/workflows/deploy.yml"
echo ""
echo "📋 Next steps to complete setup:"
echo ""
echo "1. Go to your GitHub repository: https://github.com/your-username/BluecoinsWeb"
echo ""
echo "2. Click: Settings → Secrets and variables → Actions"
echo ""
echo "3. Add these 3 repository secrets:"
echo "   ┌─────────────────┬──────────────────────────────────────┐"
echo "   │ Secret Name     │ Value                                │"
echo "   ├─────────────────┼──────────────────────────────────────┤"
echo "   │ AWS_HOST        │ $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "YOUR_EC2_PUBLIC_IP")"
echo "   │ AWS_USERNAME    │ $(whoami)                                     │"
echo "   │ AWS_SSH_KEY     │ (Paste your private .pem key content)   │"
echo "   └─────────────────┴──────────────────────────────────────┘"
echo ""
echo "4. Commit and push the workflow file:"
echo "   git add .github/workflows/deploy.yml"
echo "   git commit -m \"Add GitHub Actions auto-deployment\""
echo "   git push origin main"
echo ""
echo "5. Test the deployment:"
echo "   - Make any small change to your code"
echo "   - git add ."
echo "   - git commit -m \"Test auto-deployment\""
echo "   - git push origin main"
echo "   - Check GitHub Actions tab to see the deployment in progress"
echo ""
echo "🎉 That's it! Every push to main will now auto-deploy to AWS."
echo ""
echo "📊 Useful links:"
echo "  - View deployments: https://github.com/your-username/BluecoinsWeb/actions"
echo "  - Monitor logs: sudo journalctl -u bluecoins-web -f"
echo "  - Manual update: ./deploy/update.sh"
echo ""
